/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VolunteersRouteImport } from './routes/volunteers'
import { Route as TimeAwayRouteImport } from './routes/time-away'
import { Route as SystemAdminRouteImport } from './routes/system-admin'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SchedulingRouteImport } from './routes/scheduling'
import { Route as RosterRouteImport } from './routes/roster'
import { Route as MinistriesRouteImport } from './routes/ministries'
import { Route as LeadersRouteImport } from './routes/leaders'
import { Route as EventsRouteImport } from './routes/events'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SystemAdminIndexRouteImport } from './routes/system-admin.index'
import { Route as SystemAdminVolunteersRouteImport } from './routes/system-admin.volunteers'
import { Route as SystemAdminSchedulingRouteImport } from './routes/system-admin.scheduling'
import { Route as SystemAdminInvitesRouteImport } from './routes/system-admin.invites'
import { Route as SystemAdminChurchesRouteImport } from './routes/system-admin.churches'

const VolunteersRoute = VolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => rootRouteImport,
} as any)
const TimeAwayRoute = TimeAwayRouteImport.update({
  id: '/time-away',
  path: '/time-away',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAdminRoute = SystemAdminRouteImport.update({
  id: '/system-admin',
  path: '/system-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SchedulingRoute = SchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => rootRouteImport,
} as any)
const RosterRoute = RosterRouteImport.update({
  id: '/roster',
  path: '/roster',
  getParentRoute: () => rootRouteImport,
} as any)
const MinistriesRoute = MinistriesRouteImport.update({
  id: '/ministries',
  path: '/ministries',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersRoute = LeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemAdminIndexRoute = SystemAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SystemAdminRoute,
} as any)
const SystemAdminVolunteersRoute = SystemAdminVolunteersRouteImport.update({
  id: '/volunteers',
  path: '/volunteers',
  getParentRoute: () => SystemAdminRoute,
} as any)
const SystemAdminSchedulingRoute = SystemAdminSchedulingRouteImport.update({
  id: '/scheduling',
  path: '/scheduling',
  getParentRoute: () => SystemAdminRoute,
} as any)
const SystemAdminInvitesRoute = SystemAdminInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => SystemAdminRoute,
} as any)
const SystemAdminChurchesRoute = SystemAdminChurchesRouteImport.update({
  id: '/churches',
  path: '/churches',
  getParentRoute: () => SystemAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/assignments': typeof AssignmentsRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/leaders': typeof LeadersRoute
  '/ministries': typeof MinistriesRoute
  '/roster': typeof RosterRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/system-admin': typeof SystemAdminRouteWithChildren
  '/time-away': typeof TimeAwayRoute
  '/volunteers': typeof VolunteersRoute
  '/system-admin/churches': typeof SystemAdminChurchesRoute
  '/system-admin/invites': typeof SystemAdminInvitesRoute
  '/system-admin/scheduling': typeof SystemAdminSchedulingRoute
  '/system-admin/volunteers': typeof SystemAdminVolunteersRoute
  '/system-admin/': typeof SystemAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/assignments': typeof AssignmentsRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/leaders': typeof LeadersRoute
  '/ministries': typeof MinistriesRoute
  '/roster': typeof RosterRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/time-away': typeof TimeAwayRoute
  '/volunteers': typeof VolunteersRoute
  '/system-admin/churches': typeof SystemAdminChurchesRoute
  '/system-admin/invites': typeof SystemAdminInvitesRoute
  '/system-admin/scheduling': typeof SystemAdminSchedulingRoute
  '/system-admin/volunteers': typeof SystemAdminVolunteersRoute
  '/system-admin': typeof SystemAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/assignments': typeof AssignmentsRoute
  '/auth': typeof AuthRoute
  '/events': typeof EventsRoute
  '/leaders': typeof LeadersRoute
  '/ministries': typeof MinistriesRoute
  '/roster': typeof RosterRoute
  '/scheduling': typeof SchedulingRoute
  '/settings': typeof SettingsRoute
  '/system-admin': typeof SystemAdminRouteWithChildren
  '/time-away': typeof TimeAwayRoute
  '/volunteers': typeof VolunteersRoute
  '/system-admin/churches': typeof SystemAdminChurchesRoute
  '/system-admin/invites': typeof SystemAdminInvitesRoute
  '/system-admin/scheduling': typeof SystemAdminSchedulingRoute
  '/system-admin/volunteers': typeof SystemAdminVolunteersRoute
  '/system-admin/': typeof SystemAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/assignments'
    | '/auth'
    | '/events'
    | '/leaders'
    | '/ministries'
    | '/roster'
    | '/scheduling'
    | '/settings'
    | '/system-admin'
    | '/time-away'
    | '/volunteers'
    | '/system-admin/churches'
    | '/system-admin/invites'
    | '/system-admin/scheduling'
    | '/system-admin/volunteers'
    | '/system-admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/assignments'
    | '/auth'
    | '/events'
    | '/leaders'
    | '/ministries'
    | '/roster'
    | '/scheduling'
    | '/settings'
    | '/time-away'
    | '/volunteers'
    | '/system-admin/churches'
    | '/system-admin/invites'
    | '/system-admin/scheduling'
    | '/system-admin/volunteers'
    | '/system-admin'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/assignments'
    | '/auth'
    | '/events'
    | '/leaders'
    | '/ministries'
    | '/roster'
    | '/scheduling'
    | '/settings'
    | '/system-admin'
    | '/time-away'
    | '/volunteers'
    | '/system-admin/churches'
    | '/system-admin/invites'
    | '/system-admin/scheduling'
    | '/system-admin/volunteers'
    | '/system-admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AssignmentsRoute: typeof AssignmentsRoute
  AuthRoute: typeof AuthRoute
  EventsRoute: typeof EventsRoute
  LeadersRoute: typeof LeadersRoute
  MinistriesRoute: typeof MinistriesRoute
  RosterRoute: typeof RosterRoute
  SchedulingRoute: typeof SchedulingRoute
  SettingsRoute: typeof SettingsRoute
  SystemAdminRoute: typeof SystemAdminRouteWithChildren
  TimeAwayRoute: typeof TimeAwayRoute
  VolunteersRoute: typeof VolunteersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/volunteers': {
      id: '/volunteers'
      path: '/volunteers'
      fullPath: '/volunteers'
      preLoaderRoute: typeof VolunteersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/time-away': {
      id: '/time-away'
      path: '/time-away'
      fullPath: '/time-away'
      preLoaderRoute: typeof TimeAwayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-admin': {
      id: '/system-admin'
      path: '/system-admin'
      fullPath: '/system-admin'
      preLoaderRoute: typeof SystemAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheduling': {
      id: '/scheduling'
      path: '/scheduling'
      fullPath: '/scheduling'
      preLoaderRoute: typeof SchedulingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roster': {
      id: '/roster'
      path: '/roster'
      fullPath: '/roster'
      preLoaderRoute: typeof RosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministries': {
      id: '/ministries'
      path: '/ministries'
      fullPath: '/ministries'
      preLoaderRoute: typeof MinistriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders': {
      id: '/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof LeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system-admin/': {
      id: '/system-admin/'
      path: '/'
      fullPath: '/system-admin/'
      preLoaderRoute: typeof SystemAdminIndexRouteImport
      parentRoute: typeof SystemAdminRoute
    }
    '/system-admin/volunteers': {
      id: '/system-admin/volunteers'
      path: '/volunteers'
      fullPath: '/system-admin/volunteers'
      preLoaderRoute: typeof SystemAdminVolunteersRouteImport
      parentRoute: typeof SystemAdminRoute
    }
    '/system-admin/scheduling': {
      id: '/system-admin/scheduling'
      path: '/scheduling'
      fullPath: '/system-admin/scheduling'
      preLoaderRoute: typeof SystemAdminSchedulingRouteImport
      parentRoute: typeof SystemAdminRoute
    }
    '/system-admin/invites': {
      id: '/system-admin/invites'
      path: '/invites'
      fullPath: '/system-admin/invites'
      preLoaderRoute: typeof SystemAdminInvitesRouteImport
      parentRoute: typeof SystemAdminRoute
    }
    '/system-admin/churches': {
      id: '/system-admin/churches'
      path: '/churches'
      fullPath: '/system-admin/churches'
      preLoaderRoute: typeof SystemAdminChurchesRouteImport
      parentRoute: typeof SystemAdminRoute
    }
  }
}

interface SystemAdminRouteChildren {
  SystemAdminChurchesRoute: typeof SystemAdminChurchesRoute
  SystemAdminInvitesRoute: typeof SystemAdminInvitesRoute
  SystemAdminSchedulingRoute: typeof SystemAdminSchedulingRoute
  SystemAdminVolunteersRoute: typeof SystemAdminVolunteersRoute
  SystemAdminIndexRoute: typeof SystemAdminIndexRoute
}

const SystemAdminRouteChildren: SystemAdminRouteChildren = {
  SystemAdminChurchesRoute: SystemAdminChurchesRoute,
  SystemAdminInvitesRoute: SystemAdminInvitesRoute,
  SystemAdminSchedulingRoute: SystemAdminSchedulingRoute,
  SystemAdminVolunteersRoute: SystemAdminVolunteersRoute,
  SystemAdminIndexRoute: SystemAdminIndexRoute,
}

const SystemAdminRouteWithChildren = SystemAdminRoute._addFileChildren(
  SystemAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AssignmentsRoute: AssignmentsRoute,
  AuthRoute: AuthRoute,
  EventsRoute: EventsRoute,
  LeadersRoute: LeadersRoute,
  MinistriesRoute: MinistriesRoute,
  RosterRoute: RosterRoute,
  SchedulingRoute: SchedulingRoute,
  SettingsRoute: SettingsRoute,
  SystemAdminRoute: SystemAdminRouteWithChildren,
  TimeAwayRoute: TimeAwayRoute,
  VolunteersRoute: VolunteersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
